name: some things

env:
  EMAIL: 80916557+illogicalapple@users.noreply.github.com
  NAME: illogicalapple

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - run: git config --global user.email $EMAIL
    - run: git config --global user.name $NAME
    - run: npm install
    - run: npm run deploy
