name: some things

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - run: git config remote.origin.url 'https://illogicalapple:${{ secrets.ACCESS_TOKEN }}@github.com/text-based-scratch/bs3-gui'
    - run: git config --global user.email "80916557+illogicalapple@users.noreply.github.com"
    - run: git config --global user.name "i am a robot"
    - run: npm install
    - run: npm run deploy
